[pytest]
minversion = 8.0
addopts = -ra

testpaths =
    tests

python_files =
    test_*.py

python_classes =
    Test*

python_functions =
    test_*

markers =
    ui: pruebas end-to-end de interfaz grafica
    api: pruebas de servicios y endpoints
    smoke: pruebas criticas de validacion rapida
    regression: pruebas completas de no regresion
